### ISSUE TITLE
Stoped working?

### ISSUE THREAD

**Issue by fdnovaes** [yawo/courserax#1]
It's been a few days that it is not working anymore. It creates the directories structure, files, but it does not perform the download, so the files remain empty (0 bytes). Anyone else having this issue?

**Comment by yawo** [comment]
Yes. I'm working on it.

**Comment by yawo** [comment]
@fdnovaes Can I ask you to have a look at this one and test it ?
https://addons.mozilla.org/en-US/firefox/addon/courserax/versions/?page=1#version-2.0.0

Thanks.

**Comment by fdnovaes** [comment]
Seems to be working nicely. Thakns!

**Comment by yawo** [comment]
great !
thanks.
